// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: predict.proto

#include "predict.pb.h"
#include "predict.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace predictor {

static const char* Predictor_method_names[] = {
  "/predictor.Predictor/Predict",
};

std::unique_ptr< Predictor::Stub> Predictor::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Predictor::Stub> stub(new Predictor::Stub(channel, options));
  return stub;
}

Predictor::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Predict_(Predictor_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Predictor::Stub::Predict(::grpc::ClientContext* context, const ::predictor::PredictRequest& request, ::predictor::PredictResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::predictor::PredictRequest, ::predictor::PredictResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Predict_, context, request, response);
}

void Predictor::Stub::async::Predict(::grpc::ClientContext* context, const ::predictor::PredictRequest* request, ::predictor::PredictResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::predictor::PredictRequest, ::predictor::PredictResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Predict_, context, request, response, std::move(f));
}

void Predictor::Stub::async::Predict(::grpc::ClientContext* context, const ::predictor::PredictRequest* request, ::predictor::PredictResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Predict_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::predictor::PredictResponse>* Predictor::Stub::PrepareAsyncPredictRaw(::grpc::ClientContext* context, const ::predictor::PredictRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::predictor::PredictResponse, ::predictor::PredictRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Predict_, context, request);
}

::grpc::ClientAsyncResponseReader< ::predictor::PredictResponse>* Predictor::Stub::AsyncPredictRaw(::grpc::ClientContext* context, const ::predictor::PredictRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPredictRaw(context, request, cq);
  result->StartCall();
  return result;
}

Predictor::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Predictor_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Predictor::Service, ::predictor::PredictRequest, ::predictor::PredictResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Predictor::Service* service,
             ::grpc::ServerContext* ctx,
             const ::predictor::PredictRequest* req,
             ::predictor::PredictResponse* resp) {
               return service->Predict(ctx, req, resp);
             }, this)));
}

Predictor::Service::~Service() {
}

::grpc::Status Predictor::Service::Predict(::grpc::ServerContext* context, const ::predictor::PredictRequest* request, ::predictor::PredictResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace predictor

